use QLSVNhom
go


-- SP thêm nhân viên
CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
    @MANV VARCHAR(10),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(100),
    @LUONG VARBINARY(MAX), 
    @TENDN VARCHAR(50),
    @MK VARBINARY(MAX),    
    @PUB VARCHAR(2048)      
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
    VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK, @PUB);
END

-- Thêm mới nhân viên:
EXEC SP_INS_PUBLIC_ENCRYPT_NHANVIEN 
    'NV01', 'NGUYEN VAN A', 'NVA@', 0xDEADBEEF, 'NVA', 0xDEADBEEF, 'PUBNV1';


-- SP truy vấn nhân viên
CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
    @MANV VARCHAR(10),
    @MK VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MANV, HOTEN, EMAIL, LUONG  
    FROM NHANVIEN
    WHERE 
        MANV = @MANV AND MATKHAU = @MK
END

-- Truy vấn
EXEC SP_SEL_PUBLIC_ENCRYPT_NHANVIEN 
    'NV01', 0xDEADBEEF;