use QLSVNhom
go


-- Xóa procedure nếu đã tồn tại
IF OBJECT_ID('SP_INS_PUBLIC_ENCRYPT_NHANVIEN', 'P') IS NOT NULL
    DROP PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN;
GO

-- SP thêm nhân viên
CREATE PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
    @MANV VARCHAR(10),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(100),
    @LUONG VARBINARY(MAX), 
    @TENDN VARCHAR(50),
    @MK VARBINARY(MAX),    
    @PUB VARCHAR(2048)      
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
    VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK, @PUB);
END

-- Thêm mới nhân viên:
EXEC SP_INS_PUBLIC_ENCRYPT_NHANVIEN 
    'NV01', 'NGUYEN VAN A', 'NVA@', 0xDEADBEEF, 'NVA', 0xDEADBEEF, 'PUBNV1';



-- SP truy vấn nhân viên

-- Xóa procedure nếu đã tồn tại
IF OBJECT_ID('SP_SEL_PUBLIC_ENCRYPT_NHANVIEN', 'P') IS NOT NULL
    DROP PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN;
GO

CREATE PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
    @MANV VARCHAR(10),
    @MK VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MANV, HOTEN, EMAIL, LUONG  
    FROM NHANVIEN
    WHERE 
        MANV = @MANV AND MATKHAU = @MK
END

-- Truy vấn
EXEC SP_SEL_PUBLIC_ENCRYPT_NHANVIEN 
    'NV01', 0xDEADBEEF;




-- Xóa procedure nếu đã tồn tại
IF OBJECT_ID('SP_LOGIN_NHANVIEN', 'P') IS NOT NULL
    DROP PROCEDURE SP_LOGIN_NHANVIEN;
GO

-- 
CREATE PROCEDURE SP_LOGIN_NHANVIEN
    @MANV NVARCHAR(20),
    @MK VARBINARY(20)  -- nhận mật khẩu đã băm từ client
AS
BEGIN
    SET NOCOUNT ON;

    SELECT MANV, HOTEN, EMAIL, TENDN, PUBKEY
    FROM NHANVIEN
    WHERE MANV = @MANV AND MATKHAU = @MK;
END;
GO
