
USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'QLSVNhom')
BEGIN
    ALTER DATABASE [QLSVNhom] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [QLSVNhom];
END
GO

-- ============================
-- CREATE NEW DATABASE
-- ============================
CREATE DATABASE QLSVNhom;
GO

USE QLSVNhom;
GO

-- ============================
-- CREATE TABLES
-- ============================

CREATE TABLE SINHVIEN (
    MASV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME,
    DIACHI NVARCHAR(200),
    MALOP NVARCHAR(200),
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20),
    LUONG VARBINARY(MAX),
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL,
    PUBKEY VARCHAR(20)
);

CREATE TABLE HOCPHAN (
    MAHP VARCHAR(20) PRIMARY KEY,
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT
);

CREATE TABLE LOP (
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE BANGDIEM (
    MASV VARCHAR(20),
    MAHP VARCHAR(20),
    DIEMTHI VARBINARY(MAX),
    PRIMARY KEY (MASV, MAHP),
    FOREIGN KEY (MASV) REFERENCES SINHVIEN(MASV),
    FOREIGN KEY (MAHP) REFERENCES HOCPHAN(MAHP)
);



-- ============================
-- CREATE ENCRYPTION MATERIAL
-- ============================

-- Create MASTER KEY
IF NOT EXISTS (SELECT * FROM sys.symmetric_keys WHERE symmetric_key_id = 101)
BEGIN
    CREATE MASTER KEY ENCRYPTION BY PASSWORD = '22120429';
END;
GO

-- Create CERTIFICATE
IF NOT EXISTS (SELECT * FROM sys.certificates WHERE name = 'MYCERTIFICATE')
BEGIN
    CREATE CERTIFICATE MYCERTIFICATE
    WITH SUBJECT = 'Certificate use for create asymmetric key';
END;
GO

-- Create ASYMMETRIC KEY
IF NOT EXISTS (SELECT * FROM sys.asymmetric_keys WHERE name = 'AsymKey_NhanVien')
BEGIN
    CREATE ASYMMETRIC KEY AsymKey_NhanVien
    WITH ALGORITHM = RSA_2048
    ENCRYPTION BY PASSWORD = '22120429';
END;
GO

-- ============================
-- CREATE STORED PROCEDURES
-- ============================





-- SP_INS_PUBLIC_NHANVIEN
CREATE PROCEDURE SP_INS_PUBLIC_NHANVIEN
    @MANV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONGCB VARCHAR(100),
    @TENDN NVARCHAR(100),
    @MK NVARCHAR(100)
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MATKHAU VARBINARY(MAX) = HASHBYTES('SHA1', @MK);
    DECLARE @ASYM_KEY_ID INT = AsymKey_ID('AsymKey_NhanVien');
    DECLARE @LUONG_ENC VARBINARY(MAX) = EncryptByAsymKey(@ASYM_KEY_ID, CONVERT(VARBINARY(MAX), @LUONGCB));
    DECLARE @PUBKEY VARCHAR(20) = @MANV;

    INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
    VALUES (@MANV, @HOTEN, @EMAIL, @LUONG_ENC, @TENDN, @MATKHAU, @PUBKEY);
END;
GO









